// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk1FWYibRQ4Yqm5g2Yubiqr-GEn2ye3iM',
    appId: '1:1004795522069:web:fee5ecabda72c15527f21c',
    messagingSenderId: '1004795522069',
    projectId: 'key-space-app',
    authDomain: 'key-space-app.firebaseapp.com',
    storageBucket: 'key-space-app.firebasestorage.app',
    measurementId: 'G-VY0M5GXX5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrEixPm7BJjZWUcwQcQ1wRjN0M0ME2Lsc',
    appId: '1:1004795522069:android:f9bc6cdf5cb6ec6327f21c',
    messagingSenderId: '1004795522069',
    projectId: 'key-space-app',
    storageBucket: 'key-space-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIFyxuj6Fv5yngJ7urME_nH1OQcrAU_qA',
    appId: '1:1004795522069:ios:e9fd00dca906eb7b27f21c',
    messagingSenderId: '1004795522069',
    projectId: 'key-space-app',
    storageBucket: 'key-space-app.firebasestorage.app',
    iosBundleId: 'com.example.keySpaceApp',
  );
}
